export const products = [
	{
		id: 1,
		title: 'Nike Air Force 1 Tropical Twist',
		price: 248,
		stock: 10,
		description:
			'Combinaciones de colores elegantes y la cantidad perfecta de destello para hacerte brillar. La rica mezcla de materiales en la parte superior se combina con un logotipo swoosh similar a un derrame de aceite',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678539974/twis3_wm6k3r.jpg',
	},
	{
		id: 2,
		title: 'Nike Air Force 1 Sail Team Red',
		price: 115,
		stock: 10,
		description:
			'Celebrando 40 años de empujar los límites del deporte y la moda, este AF-1 conmemorativo combina detalles dorados, un *40* grabado en bajorrelieve en el talón y una etiqueta de honor en la lengüeta',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678110807/img01_dbm7vn.avif',
	},
	{
		id: 3,
		title: 'Nike Air Force 1 Luxe Providence Purple',
		price: 170,
		stock: 10,
		description:
			'Una parte superior de estampado animal inundado en Providence Purple es audaz, descarada e instintiva. Una suela exterior con detalles de Cavestone, una lengüeta de ante en el talón y un Swoosh de ante delineado envuelven las cosas.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111001/img01_ao5aj9.avif',
	},
	{
		id: 4,
		title: 'Nike Air Force 1 Low South Korea',
		price: 206,
		stock: 10,
		description:
			'Las zapatillas lucen un upper de color blanco adornado con el escudo del equipo en la lengüeta, la bandera de Corea del Sur en el talón y un Swoosh en los costados vestido con rayas de tigre.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111534/355495db-48b2-4de7-9dee-c2393b58a709-1ce49d859c89b649be16415755211035-1024-1024_o2ba2s.jpg',
	},
	{
		id: 5,
		title: 'Nike Air Force 1 Low Wolf Grey Kumquat',
		price: 250,
		stock: 10,
		description: 'Posee el ícono de básquetbol que celebra los 50 años del Swoosh. Tiene un diseño exclusivo con superposiciones cosidas y colores llamativos',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111053/img01_kqtdhm.avif',
	},
	{
		id: 6,
		title: 'Nike Air Force 1 Coffee',
		price: 250,
		stock: 10,
		description: 'Con una mezcla de tonos Beach, Grain, Pale Ivory y Mahogany, el tono más claro de la parte superior se compone de ante y un material similar al tejido, mientras que se adhiere a una entresuela moteada que refleja los posos del café',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111167/img01_wmdcfc.avif',
	},
	{
		id: 7,
		title: 'Nike Air Force Light Armory Blue',
		price: 94,
		stock: 10,
		description: 'Un popular tono de azul cubre esta nueva combinación de colores del calzado. La silueta de la parte superior baja está construida con cuero completamente suave en la parte superior en Light Armory Blue con detalles tonales en los cordones y el forro interior. ',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/c_scale,w_561/v1678540121/Nike-Air-Force-1-07-SE-Light-Armory-Blue-DA6682-400-Release-Date-1_zk5jyu.jpg',
	},
	{
		id: 8,
		title: 'Nike Air Force 1 Copy/Paste Pink',
		price: 129,
		stock: 10,
		description: 'Cuero blanco al igual que los cordones, la lengüeta y el forro. El Swoosh y la lengüeta del talón optan por una gamuza rosa que luego se superpone con texto repetido. También vale la pena destacar la entresuela por su acabado transparente.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/c_scale,w_512/v1678540319/X_d6773b915f4f85d9ad236f3c72f95fb2_16450278613994_lgdy3o.jpg',
	},
	{
		id: 9,
		title: 'Nike Air Force 1 Purple Agate',
		price: 170,
		stock: 10,
		description: ' El efecto desgastado de los materiales combinando colores violetas y morados les dan un aire inconfundible a las «Purple Agate». Con un swoosh reinventado que busca ir un poco más allá de la clásica costura que encontraríamos en el modelo original',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111383/img01_rbxjrx.avif',
	},
];
