export const products = [
	{
		id: 1,
		title: 'Nike Air Force 1 Tropical Twist',
		price: 248,
		stock: 10,
		description:
			'Combinaciones de colores elegantes y la cantidad perfecta de destello para hacerte brillar. La rica mezcla de materiales en la parte superior se combina con un logotipo swoosh similar a un derrame de aceite',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678539974/twis3_wm6k3r.jpg',
	},
	{
		id: 2,
		title: 'Nike Air Force 1 Sail Team Red',
		price: 115,
		stock: 10,
		description:
			'Celebrando 40 años de empujar los límites del deporte y la moda, este AF-1 conmemorativo combina detalles dorados, un *40* grabado en bajorrelieve en el talón y una etiqueta de honor en la lengüeta',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678110807/img01_dbm7vn.avif',
	},
	{
		id: 3,
		title: 'Nike Air Force 1 Luxe Providence Purple',
		price: 170,
		stock: 10,
		description:
			'Una parte superior de estampado animal inundado en Providence Purple es audaz, descarada e instintiva. Una suela exterior con detalles de Cavestone, una lengüeta de ante en el talón y un Swoosh de ante delineado envuelven las cosas.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111001/img01_ao5aj9.avif',
	},
	{
		id: 4,
		title: 'Nike Air Force 1 Low South Korea',
		price: 206,
		stock: 10,
		description:
			'Las zapatillas lucen un upper de color blanco adornado con el escudo del equipo en la lengüeta, la bandera de Corea del Sur en el talón y un Swoosh en los costados vestido con rayas de tigre.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111534/355495db-48b2-4de7-9dee-c2393b58a709-1ce49d859c89b649be16415755211035-1024-1024_o2ba2s.jpg',
	},
	{
		id: 5,
		title: 'Nike Air Force 1 Low Wolf Grey Kumquat',
		price: 250,
		stock: 10,
		description: 'Posee el ícono de básquetbol que celebra los 50 años del Swoosh. Tiene un diseño exclusivo con superposiciones cosidas y colores llamativos',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111053/img01_kqtdhm.avif',
	},
	{
		id: 6,
		title: 'Nike Air Force 1 Coffee',
		price: 250,
		stock: 10,
		description: 'Con una mezcla de tonos Beach, Grain, Pale Ivory y Mahogany, el tono más claro de la parte superior se compone de ante y un material similar al tejido, mientras que se adhiere a una entresuela moteada que refleja los posos del café.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111167/img01_wmdcfc.avif',
	},
	{
		id: 7,
		title: 'Nike Air Force Light Armory Blue',
		price: 94,
		stock: 10,
		description: 'Un popular tono de azul cubre esta nueva combinación de colores del calzado. La silueta de la parte superior baja está construida con cuero completamente suave en la parte superior en Light Armory Blue con detalles tonales en los cordones y el forro interior. ',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/c_scale,w_561/v1678540121/Nike-Air-Force-1-07-SE-Light-Armory-Blue-DA6682-400-Release-Date-1_zk5jyu.jpg',
	},
	{
		id: 8,
		title: 'Nike Air Force 1 Copy/Paste Pink',
		price: 129,
		stock: 10,
		description: 'Cuero blanco al igual que los cordones, la lengüeta y el forro. El Swoosh y la lengüeta del talón optan por una gamuza rosa que luego se superpone con texto repetido. También vale la pena destacar la entresuela por su acabado transparente.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/c_scale,w_512/v1678540319/X_d6773b915f4f85d9ad236f3c72f95fb2_16450278613994_lgdy3o.jpg',
	},
	{
		id: 9,
		title: 'Nike Air Force 1 Purple Agate',
		price: 170,
		stock: 10,
		description: ' El efecto desgastado de los materiales combinando colores violetas y morados les dan un aire inconfundible a las «Purple Agate». Con un swoosh reinventado que busca ir un poco más allá de la clásica costura que encontraríamos en el modelo original.',
		category: 'Nike',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678111383/img01_rbxjrx.avif',
	},
	{
		id: 10,
		title: 'Jordan 1 High Zoom Air CMFT 25 Years In China',
		price: 144,
		stock: 10,
		description: ' Este aniversario Zoom Air Jordan 1 rinde homenaje a la presencia de la marca en el país. Tiene un fondo blanco fuerte con superposiciones de colores que se asemejan a pinceladas en los emblemas Swoosh recortados, así como en los cuellos.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113283/img36_hbajpo.avif',
	},
	{
		id: 11,
		title: 'Jordan 1 Retro High OG Heritage',
		price: 145,
		stock: 10,
		description: 'El Air Jordan 1 Retro High OG Heritage le da la vuelta a la combinación de colores original de Chicago para lograr un estilo atrevido y único. Cuenta con una parte superior de cuero liso en blanco y rojo universitario con collares de cuero negro y Swooshes rojos. ',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113293/img36_sqnrk6.avif',
	},
	{
		id: 12,
		title: 'Jordan 4 Retro Infrared ',
		price: 257,
		stock: 10,
		description: ' El tono neón eléctrico, que saltó a la fama en otro clásico de Tinker Hatfield, combina de maravilla con los distintos tonos de gris para conseguir un estilo atrevido y fácil de combinar.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113270/img01_nzfuhd.avif',
	},
	{
		id: 13,
		title: 'Jordan 1 Retro High Court Purple ',
		price: 125,
		stock: 10,
		description: ' El Air Jordan 1 Court Purple (W) para mujer presenta una parte superior de cuero blanco con toques de Court Purple en el Swoosh y el cuello. A partir de ahí, un logotipo de Court Purple Wings se destaca en el tobillo, similar a otros Jordan 1 clásicos. ',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113258/img36_wpwgwi.avif',
	},
	{
		id: 14,
		title: 'Jordan 4 Retro Lightning',
		price: 108,
		stock: 10,
		description: ' Es una de las combinaciones de colores retro Jordan 4 más reconocidas en el catálogo de la marca Jordan. Cuenta con una parte superior Tour Yellow Durabuck con paneles de red negros y ojales gris oscuro. En la lengüeta, un parche con el logo Jordan Flight negro con detalles en blanco y amarillo complementa la parte superior.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113231/Air-Jordan-4-Retro-Lightning-2021-PS-Product_sdgxhk.avif',
	},
	{
		id: 15,
		title: 'Jordan 1 Mid Laser Blue',
		price: 294,
		stock: 10,
		description: ' Con sus detalles en negro adornando sutilmente el cuello. En cuanto al Nike Swoosh, está hecho de cuero negro. El azul láser inspirado en los Hornets aparece en el borde superior del cuello, el logotipo Wings Air Jordan, partes del forro, la suela exterior, la plantilla y el icónico Jumpman en la lengüeta.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113180/img01_kxgeun.avif',
	},
	{
		id: 16,
		title: 'Jordan 5 Retro WNBA Pinksicle Safety Orange ',
		price: 142,
		stock: 10,
		description: ' Está hecho con un material de cuero sintético con un diseño en blanco, rosa y naranja La lengüeta de la zapatilla está diseñada con malla y red translúcida, detalles en rosa y naranja, encaje de color naranja brillante y rosa translúcido en la suela exterior. ',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113242/Air-Jordan-5-Retro-WNBA-Pinksicle-Safety-Orange-GS_qpxbbp.avif',
	},
	{
		id: 17,
		title: 'Jordan 4 Retro Canyon Purple',
		price: 298,
		stock: 10,
		description: ' Su gamuza suave en color morado cañón define su estilo, y la entresuela y los ojales moteados.  Mientras tanto, un destello de color naranja seguridad se combina con toques de color verde caimán para darle un estilo funcional. ',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113152/img01_bblthb.avif',
	},
	{
		id: 18,
		title: 'Jordan 4 Retro Off-White Sail',
		price: 2717,
		stock: 10,
		description: 'Virgil Abloh está de regreso con otra creación deconstruida. El cuero de plena flor y la malla de rejilla cubren la parte superior del calzado, con un textil transparente que agrega una sutil capa de modernidad. Los cordones y la amortiguación Air están estampados con texto en negrita y mayúscula ',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678710518/img01_to0da9.avif',
	},
	{
		id: 19,
		title: 'Jordan 1 Retro High Light Smoke Grey',
		price: 215,
		stock: 10,
		description: ' Las Jordan 1 High Light Smoke Grey estan compuestas por una parte superior de cuero blanco con superposiciones de gamuza gris y un panel de tobillo de cuero rojo.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678710495/img01_kia3xy.avif',
	},
	{
		id: 20,
		title: 'Jordan 1 Low SE Arctic Punch',
		price: 204,
		stock: 10,
		description: ' La elegante base blanca de la parte superior de cuero se complementa con superposiciones de color rosa flexible en el lado medio, guardabarros y un Nike Swoosh lila. Este último tono se refleja en el emblema Wings cosido en el talón y un ícono de Jumpman en la etiqueta de la lengüeta.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113164/img01_zehpam.avif',
	},
	{
		id: 21,
		title: 'Jordan 1 Mid SE Ice Blue',
		price: 145,
		stock: 10,
		description: ' Con una construcción de cuero completo que es elegante y suave al tacto, este Air Jordan 1 está pintado predominantemente en blanco. Los tonos azul hielo se congelan sobre el área del tobillo, el talón y la puntera, mientras que los cordones complementarios unen todo.',
		category: 'Jordan',
		img: 'https://res.cloudinary.com/dn3csswh5/image/upload/v1678113316/Air-Jordan-1-Mid-Ice-Blue_q5ih6n.avif',
	},
];
